<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="8.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CBT3_Domain\CBT3_Domain.csproj" />
    <ProjectReference Include="..\CBT3_Shared\CBT3_Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include=" Microsoft.Extensions.Logging" />
    <Using Include="CBT3_Domain.Common" />
    <Using Include="CBT3_Domain.Entities" />
    <Using Include="CBT3_Domain.Enums" />
    <Using Include="CBT3_Domain.ValueObjects" />
    <Using Include="CBT3_Infrastructure.Common" />
    <Using Include="CBT3_Infrastructure.Services" />
	<Using Include="CBT3_Infrastructure.Repositories" />
    <Using Include="CBT3_Shared" />
    <Using Include="CBT3_Shared.Common" />
    <Using Include="Microsoft.Extensions.Configuration" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="System.Data" />
    <Using Include="System.Data.SqlClient" />
    <Using Include="System.Reflection" />
    <Using Include="System.Xml" />
  </ItemGroup>

</Project>
