<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <!-- Version Information -->
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <AssemblyTitle>SMS Presentation Layer</AssemblyTitle>
    <Product>PDX Safety Management System</Product>
    <Company>Portland International Airport</Company>
    <Copyright>Copyright © 2024 Portland International Airport</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Pages\SMSRiskManagement\Deprecated_Reports.razor.cs" />
    <Compile Remove="Components\Pages\SMSRiskManagement\HazardReporting.cshtml.cs" />
    <Compile Remove="Components\Pages\SMSRiskManagement\HybridRiskAssessment.razor.cs" />
    <Compile Remove="Components\Pages\SMSRiskManagement\MitigationListing.razor.cs" />
    <Compile Remove="Components\Pages\SMSRiskManagement\MyInterviewsSimple.razor.cs" />
    <Compile Remove="Components\Pages\SMSRiskManagement\PreliminaryRiskAssessment.razor.cs" />
    <Compile Remove="Components\Pages\System\UserRoles\UserRoleManagement.cshtml.cs" />
    <Compile Remove="Components\Shared\UIHelpers.cs" />
    <Compile Remove="Configuration\SwaggerConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\Counter.razor" />
    <Content Remove="Components\Pages\SMSRiskManagement\Components\HazardLocationCard.razor" />
    <Content Remove="Components\Pages\SMSRiskManagement\Components\HazardLocationDialog.razor" />
    <Content Remove="Components\Pages\SMSRiskManagement\Components\ReportEdit.razor" />
    <Content Remove="Components\Pages\SMSRiskManagement\Deprecated_Reports.razor" />
    <Content Remove="Components\Pages\SMSRiskManagement\HybridRiskAssessment.razor" />
    <Content Remove="Components\Pages\SMSRiskManagement\MyInterviewsSimple.razor" />
    <Content Remove="Components\Pages\SMSRiskManagement\PreliminaryRiskAssessment.razor" />
    <Content Remove="Components\Pages\System\UserRoles\UserRoleManagement.cshtml" />
    <Content Remove="Components\Pages\Weather.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Components\Pages\SMSRiskManagement\Deprecated_Reports.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Radzen.Blazor" Version="8.3.8" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.csproj" />
    <ProjectReference Include="..\..\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\SMSPromotion\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
