//-----------------------------------------------------------------------
// <copyright file="MitigationOverdueEvent.cs" company="SMS Safety Management System">
//     Author: SMS Development Team
//     Copyright (c) 2024 SMS Safety Management System. All rights reserved.
//     Description: Domain event triggered when a mitigation becomes overdue.
// </copyright>
//-----------------------------------------------------------------------

using SMS_Domain.Common;
using SMS_Domain.Entities;
using SMS_Domain.Interfaces;

namespace SMS_Domain.Events;

/// <summary>
/// Domain event triggered when a mitigation becomes overdue
/// </summary>
public class MitigationOverdueEvent : BaseDomainEvent, IEventSource
{
    public override string EventType => SMS_Domain.Enums.EventType.MitigationOverdue.Value;

    /// <summary>
    /// Display name for SPI configuration dropdowns
    /// </summary>
    public string EventSourceDisplayName => SMS_Domain.Enums.EventType.MitigationOverdue;

    /// <summary>
    /// Category for grouping in UI
    /// </summary>
    public string EventSourceCategory => "SMS Domain Event";

    /// <summary>
    /// Description of data provided for SPI calculations
    /// </summary>
    public string EventSourceDescription => "Provides overdue mitigation signals for corrective action closure and execution SPI metrics";

    /// <summary>
    /// Indicates this event is automatically generated by mitigation deadline checks
    /// </summary>
    public bool IsAutomaticDataSource => true;

    /// <summary>
    /// Display ordering priority in SPI source selection
    /// </summary>
    public int DisplayPriority => 6;

    public string MitigationId { get; set; } = string.Empty;
    public string MitigationCode { get; set; } = string.Empty;
    public string HazardId { get; set; } = string.Empty;
    public DateTime DueDate { get; set; }
    public int DaysOverdue { get; set; }
    public string ReportId { get; set; } = string.Empty;
    public string AssignedTo { get; set; } = string.Empty;
    public string Priority { get; set; } = string.Empty;

    public MitigationOverdueEvent(SMSEventID id,string mitigationId, string mitigationCode, string hazardId, 
        DateTime targetCompletionDate, int daysOverdue) : base(id)
    {
        MitigationId = mitigationId;
        MitigationCode = mitigationCode;
        HazardId = hazardId;
        DueDate = targetCompletionDate;
        DaysOverdue = daysOverdue;
        
    }
}