//-----------------------------------------------------------------------
// <copyright file="ValidationDecisionMadeEvent.cs" company="SMS Safety Management System">
//     Author: SMS Development Team
//     Copyright (c) 2024 SMS Safety Management System. All rights reserved.
//     Description: Domain event triggered when a report validation decision is recorded.
// </copyright>
//-----------------------------------------------------------------------

using SMS_Domain.Common;
using SMS_Domain.Entities;
using SMS_Domain.Interfaces;

namespace SMS_Domain.Events;

public class ValidationDecisionMadeEvent : BaseDomainEvent, IEventSource
{
    public override string EventType => SMS_Domain.Enums.EventType.ValidationDecisionMade.Value;

    /// <summary>
    /// Display name for SPI configuration dropdowns
    /// </summary>
    public string EventSourceDisplayName => SMS_Domain.Enums.EventType.ValidationDecisionMade;

    /// <summary>
    /// Category for grouping in UI
    /// </summary>
    public string EventSourceCategory => "SMS Domain Event";

    /// <summary>
    /// Description of data provided for SPI calculations
    /// </summary>
    public string EventSourceDescription => "Provides report validation outcomes used for risk identification effectiveness SPI metrics";

    /// <summary>
    /// Indicates this event is automatically generated by the validation workflow
    /// </summary>
    public bool IsAutomaticDataSource => true;

    /// <summary>
    /// Display ordering priority in SPI source selection
    /// </summary>
    public int DisplayPriority => 4;

    public string ReportCode { get; set; } = string.Empty;
    public string ValidationDecision { get; set; } = string.Empty;
    public DateTime ValidatedDate { get; set; }
    public string ValidatedBy { get; set; } = string.Empty;
    public string ValidationComments { get; set; } = string.Empty;

    public ValidationDecisionMadeEvent(SMSEventID id, string reportCode, string validationDecision, DateTime validatedDate)
        : base(id)
    {
        ReportCode = reportCode;
        ValidationDecision = validationDecision;
        ValidatedDate = validatedDate;
        ReportId = reportCode;
    }
}
