# GitHub Copilot Chat Archive Script
# This script helps you systematically archive all GitHub Copilot conversations
# Author: Generated by GitHub Copilot for PDXSMS_V2 project

param(
    [Parameter(Mandatory=$false)]
    [string]$ArchiveDirectory = "docs/copilot-archive",

    [Parameter(Mandatory=$false)]
    [switch]$CreateTemplate = $false,

    [Parameter(Mandatory=$false)]
    [string]$ProjectName = "PDXSMS_V2"
)

# Function to write colored output
function Write-ColorOutput {
    param([string]$Message, [string]$Color = "White")
    Write-Host $Message -ForegroundColor $Color
}

# Function to create archive directory structure
function Initialize-ArchiveStructure {
    param([string]$BaseDir)

    Write-ColorOutput "?? Creating archive directory structure..." "Cyan"

    # Create base directory
    if (!(Test-Path $BaseDir)) {
        New-Item -ItemType Directory -Path $BaseDir -Force | Out-Null
        Write-ColorOutput "? Created base directory: $BaseDir" "Green"
    }

    # Create yearly/monthly structure
    $currentDate = Get-Date
    $year = $currentDate.Year
    $months = @("01-January", "02-February", "03-March", "04-April", "05-May", "06-June",
                "07-July", "08-August", "09-September", "10-October", "11-November", "12-December")

    # Create directories for current and previous year
    foreach ($y in @(($year - 1), $year)) {
        $yearDir = Join-Path $BaseDir $y.ToString()
        if (!(Test-Path $yearDir)) {
            New-Item -ItemType Directory -Path $yearDir -Force | Out-Null
        }

        foreach ($month in $months) {
            $monthDir = Join-Path $yearDir $month
            if (!(Test-Path $monthDir)) {
                New-Item -ItemType Directory -Path $monthDir -Force | Out-Null
            }
        }
    }

    Write-ColorOutput "? Archive structure created successfully!" "Green"
}

# Function to create conversation template
function New-ConversationTemplate {
    param([string]$Topic, [string]$Date, [string]$BaseDir)

    $dateObj = if ($Date) { [DateTime]::Parse($Date) } else { Get-Date }
    $year = $dateObj.Year
    $month = $dateObj.ToString("MM-MMMM")
    $dateStr = $dateObj.ToString("yyyy-MM-dd")

    $fileName = "$dateStr-$($Topic -replace '[^\w\-]', '-').md"
    $filePath = Join-Path $BaseDir "$year/$month/$fileName"

    $template = @"
# GitHub Copilot Chat Session
**Date:** $($dateObj.ToString("yyyy-MM-dd HH:mm:ss"))  
**Project:** $ProjectName - SMS Safety Management System  
**Topic:** $Topic  
**Session Type:** [Development/Debugging/Architecture/Feature/Bug Fix]  

## ?? Session Summary
Brief description of what was accomplished in this session...

## ?? Key Objectives
- [ ] Objective 1
- [ ] Objective 2
- [ ] Objective 3

## ?? Changes Made
### Files Modified:
- `File1.cs` - Description of changes
- `File2.razor` - Description of changes

### New Files Created:
- `NewFile.cs` - Purpose and description

## ?? Key Insights & Learnings
- Insight 1: Description
- Insight 2: Description

## ?? Issues Encountered & Solutions
### Issue 1: [Brief description]
**Problem:** Description of the problem
**Solution:** How it was resolved
**Learning:** What was learned

## ?? Technical Context
- **Framework:** .NET 8
- **Project Type:** Blazor Server
- **Architecture:** Clean Architecture (Domain/Application/Infrastructure/Presentation)
- **Key Technologies:** Entity Framework, MediatR, Radzen UI

## ?? Related Sessions
- Link to related conversations or documentation

## ?? Full Conversation
```
[PASTE THE FULL COPILOT CONVERSATION HERE]

Replace this section with the complete conversation from GitHub Copilot.
Include all questions, responses, code snippets, and explanations.
```

## ?? Session Metrics
- **Duration:** [Approximate time spent]
- **Complexity:** [Low/Medium/High]
- **Files Touched:** [Number]
- **Lines Changed:** [Approximate]

## ?? Keywords for Search
Tags: $Topic, copilot, $ProjectName, $(Get-Date -Format 'yyyy-MM')

---
*Archived from GitHub Copilot Chat on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')*
"@

    return @{
        FilePath = $filePath
        Content = $template
        FileName = $fileName
    }
}

# Function to save conversation
function Save-Conversation {
    param([string]$Topic, [string]$Content, [string]$Date, [string]$BaseDir)

    $template = New-ConversationTemplate -Topic $Topic -Date $Date -BaseDir $BaseDir

    # Replace the placeholder with actual content if provided
    if ($Content) {
        $finalContent = $template.Content -replace '\[PASTE THE FULL COPILOT CONVERSATION HERE\].*?```', $Content
    } else {
        $finalContent = $template.Content
    }

    # Ensure directory exists
    $dir = Split-Path $template.FilePath -Parent
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    # Save the file
    $finalContent | Out-File -FilePath $template.FilePath -Encoding UTF8

    return $template.FilePath
}

# Function to create index file
function New-ArchiveIndex {
    param([string]$BaseDir)

    Write-ColorOutput "?? Creating archive index..." "Cyan"

    $indexPath = Join-Path $BaseDir "README.md"
    $indexContent = @"
# GitHub Copilot Chat Archive
**Project:** $ProjectName - SMS Safety Management System  
**Archive Created:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  

## ?? Archive Structure
```
docs/copilot-archive/
??? 2024/
?   ??? 11-November/
?   ?   ??? 2024-11-03-hazard-location-fix.md
?   ?   ??? 2024-11-05-api-integration.md
?   ?   ??? ...
?   ??? 12-December/
?   ??? ...
??? 2025/
?   ??? 01-January/
?   ??? ...
??? README.md (this file)
```

## ?? Quick Search Guide
Use these commands to search your archived conversations:

### PowerShell Search Commands:
```powershell
# Search by topic
Get-ChildItem -Path "docs/copilot-archive" -Recurse -Filter "*.md" | Select-String -Pattern "hazard"

# Search by date range
Get-ChildItem -Path "docs/copilot-archive/2024/11-November" -Filter "*.md"

# Search by content
Get-ChildItem -Path "docs/copilot-archive" -Recurse -Filter "*.md" | Select-String -Pattern "CreateHazardCommandHandler"
```

### File Naming Convention:
`YYYY-MM-DD-topic-description.md`

Examples:
- `2024-11-03-hazard-location-duplicate-fix.md`
- `2024-11-05-powershell-csv-import-script.md`
- `2024-11-10-report-modal-map-enhancement.md`

## ?? Archive Statistics
- **Total Conversations:** [Update manually]
- **Date Range:** 2024-11-03 to $(Get-Date -Format 'yyyy-MM-dd')
- **Project Phase:** Production Development
- **Primary Focus Areas:** SMS Safety Management, Hazard Reporting, Risk Assessment

## ?? Most Important Sessions
### Major Features & Fixes:
1. **Hazard Location Duplicate Fix** - `2024-11-XX-hazard-location-duplicate-fix.md`
2. **PowerShell CSV Import Script** - `2024-11-XX-powershell-import-script.md`
3. **Report Modal Map Enhancement** - `2024-11-XX-report-modal-map-enhancement.md`

### Architecture Decisions:
- Clean Architecture implementation
- CQRS pattern usage
- API design patterns

## ?? Related Documentation
- Main project: `C:\Projects\PDXSMS_V2\`
- Repository: https://github.com/scottmgreen/CBT3
- Framework: .NET 8 Blazor Server

---
*This archive contains valuable development insights and problem-solving approaches used in the PDXSMS_V2 project.*
"@

    $indexContent | Out-File -FilePath $indexPath -Encoding UTF8
    Write-ColorOutput "? Archive index created: $indexPath" "Green"

    return $indexPath
}

# Function to create bulk import helper
function New-BulkImportHelper {
    param([string]$BaseDir)

    $helperPath = Join-Path $BaseDir "bulk-import-helper.ps1"
    $helperContent = @"
# Bulk Import Helper for Copilot Conversations
# Use this script to quickly add multiple conversations

param([string]`$Topic, [string]`$Date)

if (-not `$Topic) {
    Write-Host "Usage: .\bulk-import-helper.ps1 -Topic 'Description of conversation' -Date '2024-11-03'" -ForegroundColor Yellow
    Write-Host "Then paste your conversation content when prompted" -ForegroundColor Yellow
    exit
}

Write-Host "?? Creating new conversation archive for: `$Topic" -ForegroundColor Green
Write-Host "?? Date: `$Date" -ForegroundColor Cyan
Write-Host ""
Write-Host "?? Please paste your complete Copilot conversation below." -ForegroundColor Yellow
Write-Host "   Press Ctrl+Z then Enter when finished:" -ForegroundColor Yellow
Write-Host ""

`$content = @()
do {
    `$line = Read-Host
    if (`$line -ne `$null) { `$content += `$line }
} while (`$line -ne `$null)

`$conversationText = `$content -join "`n"

# Save the conversation
. .\Archive-CopilotChats.ps1
`$savedPath = Save-Conversation -Topic `$Topic -Content `$conversationText -Date `$Date -BaseDir "."

Write-Host "? Conversation saved to: `$savedPath" -ForegroundColor Green
"@

    $helperContent | Out-File -FilePath $helperPath -Encoding UTF8
    Write-ColorOutput "??? Bulk import helper created: $helperPath" "Green"
}

# Main execution
Write-ColorOutput "?? GitHub Copilot Chat Archive Tool" "Green"
Write-ColorOutput "Project: $ProjectName" "Cyan"
Write-ColorOutput "Archive Directory: $ArchiveDirectory" "Cyan"
Write-ColorOutput ""

try {
    # Initialize archive structure
    Initialize-ArchiveStructure -BaseDir $ArchiveDirectory

    # Create index
    $indexPath = New-ArchiveIndex -BaseDir $ArchiveDirectory

    # Create bulk import helper
    New-BulkImportHelper -BaseDir $ArchiveDirectory

    if ($CreateTemplate) {
        # Create a sample template
        $samplePath = Save-Conversation -Topic "Sample-Conversation" -Date (Get-Date).ToString("yyyy-MM-dd") -BaseDir $ArchiveDirectory
        Write-ColorOutput "?? Sample template created: $samplePath" "Green"
    }

    Write-ColorOutput ""
    Write-ColorOutput "?? Archive setup complete!" "Green"
    Write-ColorOutput ""
    Write-ColorOutput "?? Next Steps:" "Yellow"
    Write-ColorOutput "1. Navigate to your archive directory: $ArchiveDirectory" "White"
    Write-ColorOutput "2. Use bulk-import-helper.ps1 for quick conversation imports" "White"
    Write-ColorOutput "3. Follow the naming convention: YYYY-MM-DD-topic-description.md" "White"
    Write-ColorOutput "4. Update the README.md index as you add conversations" "White"
    Write-ColorOutput ""
    Write-ColorOutput "?? Pro tip: Start with your most recent/important conversations first!" "Cyan"

} catch {
    Write-ColorOutput "? Error: $($_.Exception.Message)" "Red"
    exit 1
}

# Export key functions for use in other scripts
Export-ModuleMember -Function Save-Conversation, New-ConversationTemplate, Initialize-ArchiveStructure